"use client";

import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import { Layout } from "../layout/Layout";
import "../(site)/globals.css";

// export const metadata = {
//     title: "Universal Motors",
//     description: "Generated by create next app",
// };

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function SiteLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <title>Universal Motors</title>
                <link rel="icon" href="/umico.png" />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                {/* Убираем SessionWrapper */}
                <SessionProvider>
                    <Layout>{children}</Layout>
                </SessionProvider>
            </body>
        </html>
    );
}
