// app/layout.tsx
import { SessionProvider } from "next-auth/react"; // Импортируем SessionProvider
import { Geist, Geist_Mono } from "next/font/google";

// Пример перемещения metadata в серверный компонент, чтобы избежать ошибки с "use client"
export const metadata = {
    title: "Universal Motors",
    description: "Generated by create next app",
};

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Оборачиваем все в SessionProvider только на клиенте
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SessionWrapper>{children}</SessionWrapper>
            </body>
        </html>
    );
}

// Создаём компонент для обёртки на клиенте
function SessionWrapper({ children }: { children: React.ReactNode }) {
    if (typeof window === "undefined") {
        return <>{children}</>; // Серверная часть не использует SessionProvider
    }

    return <SessionProvider>{children}</SessionProvider>;
}
